Implements the provider side of n2
canonical/sdcore-amf-operator pull request #9
Opened 2023-06-05 09:05 UTC by saltiyazan

# Description

Implements the provider side of the N2 relation interface in the AMF charm.

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have bumped the version of the library

2023-06-05 11:26 UTC, Gmerold approved these changes

2023-06-06 15:15 UTC, gruyaume requested changes

2023-06-06 15:15 UTC, gruyaume commented on src/charm.py
> +        if not self._relation_created(N2_RELATION_NAME):
Also, in the unit tests, please include cases where there's more than 1 requirer to catch this.

2023-06-07 08:09 UTC, saltiyazan commented on src/charm.py
> +        if not self._relation_created(N2_RELATION_NAME):
Good catch, Fixed it.

2023-06-07 13:26 UTC, merged